# Generated by Django 4.2.1 on 2023-08-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='GFG',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='LeetCode',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='Linkedin',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='Resume',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='insta',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='portfolio',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='twitter',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
