# Generated by Django 4.2.1 on 2023-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userinformation_facebook_userinformation_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='codepen',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
