# Generated by Django 4.2.1 on 2023-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userinformation_codepen_userinformation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='website',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
