# Generated by Django 4.2.1 on 2023-09-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userinformation_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='codechef',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
