# Generated by Django 4.2.1 on 2023-09-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userinformation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='GFG',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='LeetCode',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='Linkedin',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='Resume',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='codechef',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='codepen',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='facebook',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='github',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='hackerrank',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='insta',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='mail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='portfolio',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='role',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='twitter',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='website',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
